# by David Reguera Garcia aka Dreg dreg@fr33project.org
# https://github.com/therealdreg https://www.fr33project.org @therealdreg

all: 
	nasm -f bin multi_core_startup.asm -o multi_core_startup.bin

clean: 
	rm -f multi_core_startup.bin